# docker-compose version
version: '3.3'

# computes
services:
  simba:
    build:
      context: .
      dockerfile: ./Dockerfile-conda
    image: simba-python36
    environment:
      # only works for Linux
      DISPLAY:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix #Static - needed to display atom on your host
      - ./videos:/app/videos
      - ./output:/app/output
      #- ../../3rd/simba/simba:/code/simba
      - ./template-config.ini:/app/template-config.ini
      - ./main.py:/app/main.py

    command: /opt/conda/envs/simba/bin/simba

  deep:
    build:
      context: .
      dockerfile: ./Dockerfile-deep
    image: deeplabcut-python37
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output

    command: python -m deeplabcut
