# docker-compose version
version: '3.3'

# computes
services:
  simba:
    build:
      context: .
      dockerfile: ./Dockerfile-simba
    image: simba-python36
    environment:
      # only works for Linux
      DISPLAY:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix #Static - needed to display atom on your host
      - ./videos:/app/videos
      - ./output:/app/output
      #- ../../3rd/simba/simba:/code/simba
      - ./template-config.ini:/app/template-config.ini
      - ./main.py:/app/main.py

    command: /opt/conda/envs/simba/bin/simba

  deep:
    # use official image
    #image: deeplabcut/deeplabcut:latest-gui

    # if to build your own
    build:
      context: .
      dockerfile: ./Dockerfile-deep
    image: deeplabcut-python36
    command: /opt/conda/envs/DLC-CPU/bin/python -m deeplabcut

    # common regardless image
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix #Static - needed to display atom on your host
      - ./videos:/app/videos
      - ./output:/app/output

    environment:
      # only works for Linux
      DISPLAY:


  project:
    build:
      context: .
      dockerfile: ./Dockerfile-taskjuggler
    image: taskjuggler
    volumes:
      - ./project:/project
      - ./docs/content/downloads:/reports
    command: tj3 main.tjp
