# docker-compose version
version: '3.3'

# computes
services:
  simba:
    build:
      context: .
      dockerfile: ./Dockerfile-conda
    image: simba-python36
    environment:
      # only works for Linux
      DISPLAY: unix:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix #Static - needed to display atom on your host
      - ../../3rd/simba/videos:/app/videos
      - ../../3rd/simba//output:/app/output
      - ../../3rd/simba/simba:/code/simba
      - ./main.py:/code/main.py

    command: bash -c "conda init bash && source ~/.bashrc && conda activate simba && /opt/conda/envs/simba/bin/simba"
